import json
import os
from datetime import datetime, UTC


class FrameworkBootstrapService:

    def bootstrap(
        self,
        repository_path: str,
        workspace_id: str,
        application_url: str
    ):

        self.create_folders(
            repository_path
        )

        self.create_manifest(
            repository_path
        )

        self.create_workspace_file(
            repository_path,
            workspace_id,
            application_url
        )

        self.create_readme(
            repository_path
        )

        self.create_package_json(
            repository_path
        )

        self.create_playwright_config(
            repository_path
        )

        self.create_base_fixture(
            repository_path
        )

    def create_folders(
        self,
        repository_path: str):

        folders = [

            ".directqa",

            "pages",

            "components",

            "fixtures",

            "tests",

            "tests/e2e",

            "test-data",

            "test-data/generated",

            "test-data/static",

            "constants",

            "utils",

            "reports",

            "screenshots",

            "downloads",

            "traces"
        ]

        for folder in folders:

            os.makedirs(
                os.path.join(
                    repository_path,
                    folder
                ),
                exist_ok=True
            )

    def create_manifest(
        self,
        repository_path: str):

        manifest = {

            "pages": [],

            "components": [],

            "fixtures": [],

            "tests": []
        }

        manifest_path = os.path.join(
            repository_path,
            ".directqa",
            "framework-manifest.json"
        )

        with open(
            manifest_path,
            "w"
        ) as file:

            json.dump(
                manifest,
                file,
                indent=4
            )

    def create_workspace_file(
        self,
        repository_path: str,
        workspace_id: str,
        application_url: str):

        workspace = {

            "workspaceId": workspace_id,

            "applicationUrl": application_url,

            "frameworkVersion": "1.0.0",

            "createdAt": datetime.now(UTC).isoformat()
        }

        workspace_file = os.path.join(
            repository_path,
            ".directqa",
            "workspace.json"
        )

        with open(
            workspace_file,
            "w"
        ) as file:

            json.dump(
                workspace,
                file,
                indent=4
            )

    def create_readme(
        self,
        repository_path: str):

        content = """
        # DirektQA Automation Framework

        Generated by DirektQA

        Framework:
        Playwright + TypeScript

        Managed By:
        DirektQA
        """

        path = os.path.join(
            repository_path,
            "README.md"
        )

        with open(
            path,
            "w"
        ) as file:

            file.write(
                content
            )

    def create_package_json(
        self,
        repository_path: str):

        package_json = {

            "name": "direktqa-framework",

            "version": "1.0.0",

            "scripts": {

                "test": "playwright test"
            }
        }

        path = os.path.join(
            repository_path,
            "package.json"
        )

        with open(
            path,
            "w"
        ) as file:

            json.dump(
                package_json,
                file,
                indent=4
            )

    def create_playwright_config(
        self,
        repository_path: str):

        content = """
        import { defineConfig } from '@playwright/test';

        export default defineConfig({
        testDir: './tests/e2e',
        timeout: 30000,
        retries: 1
        });
        """

        path = os.path.join(
            repository_path,
            "playwright.config.ts"
        )

        with open(
            path,
            "w"
        ) as file:

            file.write(
                content
            )

    def create_base_fixture(
        self,
        repository_path: str):

        content = """
        import { test as base } from '@playwright/test';

        export const test = base.extend({});

        export { expect } from '@playwright/test';
        """

        path = os.path.join(
            repository_path,
            "fixtures",
            "base.fixture.ts"
        )

        with open(
            path,
            "w"
        ) as file:

            file.write(
                content
            )